// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpjkmczhodcrklcrfuta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwamttY3pob2RjcmtsY3JmdXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTU3NjQsImV4cCI6MjA2Nzg3MTc2NH0.eQtGflfA8KA8H32s2gDPsZxeU7dsdmhPC1qJXuYUvGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});